.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Threading;

using MusicStore.Domain.POCO;
using MusicStore.WebUI.ViewModels;

namespace MusicStore.WebUI.Controllers
{
  public class ShoppingCartController : Controller
  {
    private MusicStore.Domain.Concrete.ShoppingCartManager manager = new MusicStore.Domain.Concrete.ShoppingCartManager();


    #region State management
    private const string CTE_Session_UserName = "UserName";

    private string CurrentUserName
    {
      get
      {
        string userName = String.Empty;

        //Check if the session already contains a userName
        if (Session[CTE_Session_UserName] == null)
        {
          //Create a username on, based on the current logged in user 
          // of if no user has logged in, create an unique number for this session
          if (Thread.CurrentPrincipal != null
                && Thread.CurrentPrincipal.Identity != null
                && !String.IsNullOrEmpty(Thread.CurrentPrincipal.Identity.Name))
          {
            userName = Thread.CurrentPrincipal.Identity.Name;
          }
          else
            userName = Guid.NewGuid().ToString();

          Session[CTE_Session_UserName] = userName;

        }
        else
          userName = Session[CTE_Session_UserName].ToString();

        return userName;
      }
    }
    #endregion

    //
    // GET: /ShoppingCart/
    public ActionResult Index()
    {
      ShoppingCart currentShoppingCart = manager.GetShoppingCartWithCartItems(this.CurrentUserName);
      if (currentShoppingCart == null) return RedirectToAction("Index", "Home");
      
      // Set up our ViewModel
      var viewModel = new ShoppingCartViewModel() 
                            {
                              CartItems = currentShoppingCart.CartItems,
                              CartTotal = manager.GetTotalPrice(CurrentUserName)
                            };

      // Return the view
      return View(viewModel);
    }

    //
    // GET: /ShoppingCart/AddToCart/5
    
    public ActionResult AddToCart(int albumIdToAdd)
    {
      manager.AddToCart(albumIdToAdd, this.CurrentUserName);

      // Go back to the main store page for more shopping
      return RedirectToAction("Index");
    }

    //
    // AJAX: /ShoppingCart/RemoveFromCart/5

    [HttpPost]
    public ActionResult RemoveFromCart(int albumIdToRemove)
    {
      // Remove the item from the cart
      var currentShoppingCart = manager.GetShoppingCartWithCartItems(this.CurrentUserName);


      // Get the name of the album to display confirmation
      string albumName = currentShoppingCart
                                          .CartItems
                                          .Find(ci => ci.AlbumId == albumIdToRemove)
                                          .Album.Title;
      
      // Remove from cart
      int itemsLeft = manager.RemoveFromCart(albumIdToRemove, this.CurrentUserName);

      // Display the confirmation message
      ShoppingCartRemoveViewModel dataToShow = new ShoppingCartRemoveViewModel()
      {
        Message = Server.HtmlEncode(albumName) +
            " has been removed from your shopping cart.",
        CartTotal = manager.GetTotalPrice(this.CurrentUserName),
        CartCount = manager.GetTotalQuantity(this.CurrentUserName),
        ItemCount = itemsLeft,
        DeleteId = albumIdToRemove
      };

      return Json(dataToShow);
    }

    //
    // GET: /ShoppingCart/CartSummary

    [ChildActionOnly]
    public ActionResult CartSummary()
    {
      ViewData["CartCount"] = manager.GetTotalQuantity(this.CurrentUserName);
      return PartialView("CartSummary");
    }
  }
}

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MusicStore.Domain.POCO;
using MusicStore.Domain.Concrete;

namespace MusicStore.WebUI.Controllers
{
    public class StoreController : Controller
    {
      EFDbContext db = new EFDbContext();
        //
        // GET: /Store/

        public ActionResult Index()
        {
          var genres = db.Genres.ToList<Genre>();
          return View(genres);
        }

        // GET: /Store/Browse
        public ActionResult Browse(string genre)
        {
          var genreModel = db.Genres.Include("Albums").Single<Genre>(x => x.Name == genre); // er zou er maar 1 mogen bestaan, first => zouden er meerdere kunnen zijn en alleen de eerste
            //include ==> verwante albums mee inladen
          return View(genreModel);
        }

        //GET: /Store/Details
        public ActionResult Details(int id)
        {
          var album = db.Albums.Include("Artist").Single<Album>(x => x.AlbumId == id);
          return View(album);
        }

    }
}

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Store/Browse.cshtml
@model MusicStore.Domain.POCO.Genre

@{
    ViewBag.Title = "Browse";
}

<h2>Browse - Genre = @Model.Name</h2>
<ul>
@foreach (var album in Model.Albums)
{
    <li>@Html.ActionLink(album.Title,"Details",new{id=album.AlbumId}) - @album.Artist.Name</li>
}
</ul>

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Store/Details.cshtml
@model MusicStore.Domain.POCO.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Album</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Price</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">AlbumArtUrl</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AlbumArtUrl)
    </div>

    <div class="display-label">Genre</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Genre.Name)
    </div>

    <div class="display-label">Artist</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Artist.Name)
    </div>
</fieldset>
<p class="button">
    @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { albumIdToAdd = Model.AlbumId }, "")
</p>

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Store/Index.cshtml
@model IEnumerable<MusicStore.Domain.POCO.Genre>

@{
    ViewBag.Title = "Index - Store";
}

<h3>Browse Genres</h3>
<p>Selecteer uit @Model.Count() genres :</p>
<ul>
    @foreach (var genre in Model)
    { 
        <li>@Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })</li>
    }
</ul>