.NET/Projects/Praktijk/PrakMVC1/WebUI/Controllers/ContextController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.POCO;
using Domain.DB;

namespace WebUI.Controllers
{ 
    public class ContextController : Controller
    {
        private GTDbContext db = new GTDbContext();

        //
        // GET: /Context/

        public ViewResult Index()
        {
            return View(db.Contexten.ToList());
        }

        //
        // GET: /Context/Details/5

        public ViewResult Details(int id)
        {
            Context context = db.Contexten.Find(id);
            return View(context);
        }

        //
        // GET: /Context/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Context/Create

        [HttpPost]
        public ActionResult Create(Context context)
        {
            if (ModelState.IsValid)
            {
                db.Contexten.Add(context);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(context);
        }
        
        //
        // GET: /Context/Edit/5
 
        public ActionResult Edit(int id)
        {
            Context context = db.Contexten.Find(id);
            return View(context);
        }

        //
        // POST: /Context/Edit/5

        [HttpPost]
        public ActionResult Edit(Context context)
        {
            if (ModelState.IsValid)
            {
                db.Entry(context).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(context);
        }

        //
        // GET: /Context/Delete/5
 
        public ActionResult Delete(int id)
        {
            Context context = db.Contexten.Find(id);
            return View(context);
        }

        //
        // POST: /Context/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Context context = db.Contexten.Find(id);
            db.Contexten.Remove(context);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

.NET/Projects/Praktijk/PrakMVC1/WebUI/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.POCO;
using Domain.DB;

namespace WebUI.Controllers
{ 
    public class ProjectController : Controller
    {
        private GTDbContext db = new GTDbContext();

        //
        // GET: /Project/

        public ViewResult Index()
        {
            var projecten = db.Projecten.Include(p => p.Context);
            return View(projecten.ToList());
        }

        //
        // GET: /Project/Details/5

        public ViewResult Details(int id)
        {
            Project project = db.Projecten.Find(id);
            return View(project);
        }

        //
        // GET: /Project/Create

        public ActionResult Create()
        {
            ViewBag.ContextId = new SelectList(db.Contexten, "ContextID", "Naam");
            return View();
        } 

        //
        // POST: /Project/Create

        [HttpPost]
        public ActionResult Create(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projecten.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.ContextId = new SelectList(db.Contexten, "ContextID", "Naam", project.ContextId);
            return View(project);
        }
        
        //
        // GET: /Project/Edit/5
 
        public ActionResult Edit(int id)
        {
            Project project = db.Projecten.Find(id);
            ViewBag.ContextId = new SelectList(db.Contexten, "ContextID", "Naam", project.ContextId);
            return View(project);
        }

        //
        // POST: /Project/Edit/5

        [HttpPost]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContextId = new SelectList(db.Contexten, "ContextID", "Naam", project.ContextId);
            return View(project);
        }

        //
        // GET: /Project/Delete/5
 
        public ActionResult Delete(int id)
        {
            Project project = db.Projecten.Find(id);
            return View(project);
        }

        //
        // POST: /Project/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Project project = db.Projecten.Find(id);
            db.Projecten.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

.NET/Projects/Praktijk/PrakMVC1/WebUI/Views/Context/Create.cshtml
@model Domain.POCO.Context

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Context</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Naam)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Naam)
            @Html.ValidationMessageFor(model => model.Naam)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Omschrijving)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Omschrijving)
            @Html.ValidationMessageFor(model => model.Omschrijving)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

.NET/Projects/Praktijk/PrakMVC1/WebUI/Views/Context/Delete.cshtml
@model Domain.POCO.Context

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Context</legend>

    <div class="display-label">Naam</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Naam)
    </div>

    <div class="display-label">Omschrijving</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Omschrijving)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

.NET/Projects/Praktijk/PrakMVC1/WebUI/Views/Context/Details.cshtml
@model Domain.POCO.Context

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Context</legend>

    <div class="display-label">Naam</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Naam)
    </div>

    <div class="display-label">Omschrijving</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Omschrijving)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ContextID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
    @foreach (var item in Model.Projecten)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Naam, "Details","Project", new { id = item.ProjectId }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Omschrijving)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
        </tr>   
    }

.NET/Projects/Praktijk/PrakMVC1/WebUI/Views/Context/Edit.cshtml
@model Domain.POCO.Context

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Context</legend>

        @Html.HiddenFor(model => model.ContextID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Naam)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Naam)
            @Html.ValidationMessageFor(model => model.Naam)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Omschrijving)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Omschrijving)
            @Html.ValidationMessageFor(model => model.Omschrijving)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

.NET/Projects/Praktijk/PrakMVC1/WebUI/Views/Context/Index.cshtml
@model IEnumerable<Domain.POCO.Context>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Naam
        </th>
        <th>
            Omschrijving
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Naam, "Details", new { id = item.ContextID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Omschrijving)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ContextID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ContextID })
        </td>
    </tr>
}

</table>