.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Domain.POCO;
using MusicStore.Domain.Concrete;

namespace MusicStore.WebUI.Controllers
{ 
    [Authorize(Roles="Administrator")]
    public class AlbumController : Controller
    {
        private EFDbContext db = new EFDbContext();

        //
        // GET: /Album/

        public ViewResult Index()
        {
            var albums = db.Albums.Include(a => a.Genre).Include(a => a.Artist);
            return View(albums.ToList());
        }

        //
        // GET: /Album/Details/5

        public ViewResult Details(int id)
        {
            Album album = db.Albums.Find(id);
            return View(album);
        }

        //
        // GET: /Album/Create

        public ActionResult Create()
        {
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            return View();
        } 

        //
        // POST: /Album/Create

        [HttpPost]
        public ActionResult Create(Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }
        
        //
        // GET: /Album/Edit/5
 
        public ActionResult Edit(int id)
        {
            Album album = db.Albums.Find(id);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // POST: /Album/Edit/5

        [HttpPost]
        public ActionResult Edit(Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            return View(album);
        }

        //
        // GET: /Album/Delete/5
 
        public ActionResult Delete(int id)
        {
            Album album = db.Albums.Find(id);
            return View(album);
        }

        //
        // POST: /Album/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Shared/DbError.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>DbError</title>
</head>
<body>
    <h2>
        A database error has occurred while processing your request.
    </h2>
</body>
</html>

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Page not found error</title>
</head>
<body>
    <h2>
       404 Page not found
    </h2>
</body>
</html>

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Shared/_Layout.cshtml
@using MusicStore.WebUI.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    @Html.MetaAcceptLanguage();
    <script type="text/javascript">
        //Tell jQuery Globalization plugin about our culture
    $(document).ready(function(){
    var data = $("meta[name='accept-language']").attr("content");
    Globalize.culture(Globalize.findClosestCulture(data));   
    
    //bind the alidator functions
    // onze jquert validatie gebruik laten maken van de globalazation plugin
    $.validator.methods.number = function(value, element){
    //parse numbers using Globalize
        if(Globalize.parseFloat(value)){
            return true;
        }
            return false;
        };
    
    });
    </script>
</head>

<body>
   <div id="header">
    <h1>
      ASP.NET MVC3 Music Store</h1>
      <div id="logindisplay">
        @Html.Partial("_LogOnPartial")
      </div>
    <ul id="navlist">
      <li class="first"><a href="/" id="current">Home</a></li>
      <li><a href="/Store/">Store</a></li>
      <li>@Html.ActionLink("Album Manager","Index","Album")</li>
</ul>
  </div>
  @RenderBody()
</body>
</html>

.NET/Projects/Praktijk/MVC3MusicStore - Copy/MusicStore.WebUI/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}